### ISSUE TITLE
Let's plan for a way to pull data from local and remote sources

### ISSUE THREAD

**Issue by petre2dor** [petre2dor/piGarden#5]
I was thinking that we could get data from all kind of external sources (yahoo, forecast.io)
One action would get local temperature, another would get current temperature and 10 days forecast from forecast.io....

**Comment by rcursaru** [comment]
So the device table should have a structure like [id] - [json describing the access to this device]. One device would have details regarding local access to it, another will have url, API keys and things like that. Sounds good!

**Comment by petre2dor** [comment]
`device` sounds too _physical_. let's save data for external services in actions. doesn't it sound better?

**Comment by rcursaru** [comment]
maybe it would be better to group local devices and external services under a common umbrella, something like "data providers". i believe it has more sense from a logical point of view to have it together, since they do provide and/or consume data: you can request the temperature either from a local sensor or from a weather/forecast provider; you can request to close all windows either by calling a local relay/electric motor/whatever or by calling a remote home automation API.
Does it make sense or am I rambling on a different tune? :)

**Comment by petre2dor** [comment]
No, it's perfect. I'll close this and open an enhancement.

**Comment by petre2dor** [comment]
let's talk about these changes on a call and open smaller tasks for each step

**Comment by petre2dor** [comment]
I consider this completed for now
